### ISSUE TITLE
Collection does not exist

### ISSUE THREAD

**Issue by Hardrada** [joachimdalen/azdevops-acceptance-criterias#20]
Hi,
I've been trying to use the extension, but when it loads, I get
![image](https://user-images.githubusercontent.com/2984126/168136962-50a5a278-e8eb-4dcc-9e94-594f60a3d61b.png)

**Comment by joachimdalen** [comment]
Hi!

By default you will get this error messages some place, but it is handled in the extension. 

This extension stores data in three different collections
- [project_id]-AcceptanceCriterias
- [project_id]-AcceptanceCriteriaDetails
- [project_id]-Settings

When the first document in the collection is created, this message will disappear. 

These errors messages will show: 
- If you are trying to load the Hub in the sidebar **without** having created any criterias (`project_id]-AcceptanceCriterias`)
- Trying to show the tab/control on the work item form  **without** having created any criterias (`project_id]-AcceptanceCriterias`)
- Loading the control/hub without having toggled any of the setting found in the project administration view (`[project_id]-Settings`).

So as soon as the extension is taken into use this error should disappear.

**Comment by joachimdalen** [comment]
I will close this due to the lack of a response. Please let me know if you still face any issues.
