### ISSUE TITLE
Add keyboard shortcuts for improved navigation and UX

### ISSUE THREAD

**Issue by xperiandri** [joachimdalen/azdevops-acceptance-criterias#25]
Current UX is very click-heavy.
In order to add a new checklist item you have to move mouse to the add button, click, then move it back to new checklist item and click again.
It would be nice if Enter key adds a new item and moves focus to it.

**Comment by joachimdalen** [comment]
Some parts of the extension could use some optimization on lowering the amount of clicks needed to perform certain actions. I'll take a look at what keyboard shortcuts makes sense to add, and will start with that one 🙂

**Comment by joachimdalen** [comment]
Hi again!

I have added some keyboard shortcuts (see excerpt from documentation below). Currently testing this and will be released later (1-3 days) as I have some other changes that will need to be included in the same release.

--- 
## Criteria Panel - Checklist & Scenario

While you have one of the text fields focused, you can use the following shortcuts

| Shortcut                             | Description                                                                                           |
| ------------------------------------ | ----------------------------------------------------------------------------------------------------- |
| <kbd>Ctrl</kbd>+<kbd>Enter</kbd>     | `Checklist`: Add a new checklist item. `Scenario`: Move the focus to the toolbar to select a new step |
| <kbd>Ctrl</kbd>+<kbd>ArrowUp</kbd>   | Move item up                                                                                          |
| <kbd>Ctrl</kbd>+<kbd>ArrowDown</kbd> | Move item down                                                                                        |
| <kbd>Ctrl</kbd>+<kbd>Delete</kbd>    | Remove item                                                                                           |

## Browser default

| Shortcut                        | Description                    |
| ------------------------------- | ------------------------------ |
| <kbd>Tab</kbd>                  | Move focus to next element     |
| <kbd>Shift</kbd>+<kbd>Tab</kbd> | Move focus to previous element |

**Comment by xperiandri** [comment]
Looks great!

**Comment by joachimdalen** [comment]
Released in `v1.2.0` :rocket:
