### ISSUE TITLE
Enable text overflow when viewing criteria

### ISSUE THREAD

**Issue by trevonmckay** [joachimdalen/azdevops-acceptance-criterias#51]
Some of the items in a checklist or scenario are rather long and users are unable to read the text as it gets truncated. Please allow the display of overflow text.

![image](https://user-images.githubusercontent.com/18320804/197813234-8a6f3b1a-19fe-468f-a0b5-8618a4256e3c.png)

**Comment by joachimdalen** [comment]
Should be a quick fix, I'll look at getting it fixed and deployed within a few days.

**Comment by joachimdalen** [comment]
Fixed the issue. It will be released as a part of a bigger release this upcoming weekend.

**Comment by joachimdalen** [comment]
Fixed and released.
